### ISSUE TITLE
Error: Unable to resolve module, Module `./src/components/field` does not exist in the Haste module map

### ISSUE THREAD

**Issue by thirappusuresh** [flisboac/react-native-monorepo-helper#1]
Getting following error when I'm using the plugin react-native-material-textfield:

error: bundling failed: Error: Unable to resolve module `./src/components/field` from `/Library/WebServer/Documents/monorepo/packages/native/node_modules/react-native-material-textfield/index.js`: Module `./src/components/field` does not exist in the Haste module map

    at ModuleResolver.resolveDependency (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/node-haste/DependencyGraph.js:219:16)
    at Object.resolve (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Library/WebServer/Documents/monorepo/packages/native/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)

**Comment by flisboac** [comment]
Hello, @thirappusuresh !

I can vaguely see that you don't hoist this dependency. From what I can see, this `react-native-material-textfield` doesn't need any extra "native" setup (i.e. messing with native project files), and that's good. :)

That's a very strange error, because both [the helper](https://github.com/flisboac/react-native-monorepo-helper/blob/81a9e1f347319be203c5915fb6aeb38932bf4ab6/src/index.ts#L341) and its dependency [`resolve`](https://www.npmjs.com/package/resolve) should be able to resolve relative imports. (Metro itself acts strange most of the time... :/ )

This may be caused by missing extensions in your configuration. My guess is that `resolve` is able to find your `react-native-material-textfield` dependency through `package.json` (and in such a case, the `main` field's file extension doesn't matter), but [Metro's `sourceExts`](https://facebook.github.io/metro/docs/en/configuration) is empty or doesn't contain the "js" extension, so it's not able to find that relative import `./src/components/field` somehow.

You could try something along the following lines. Tell me if it works:

```js
const projectRoot = __dirname;
const metroConfigHelper = require('react-native-monorepo-helper') 
    .metroConfigHelper;

module.exports = metroConfigHelper(projectRoot)
    .defaultConfig({
        // Add here any extension you may need
        sourceExts: ["js", "jsx"],
    })
    // If you use typescript, this will automatically add all the necessary plugins
    // and common extensions ("ts" and "tsx")
    .typeScript(true) 
    .generate();
```

Regardless... How is your `rn-cli.config.js` (and project) configured? Perhaps you could provide me with a minimum project that reproduces your error, if my previous suggestion doesn't work.

**Comment by thirappusuresh** [comment]
No luck, still the same error. Please find the bare minimum project to reproduce the error.
https://github.com/thirappusuresh/monorepo-native

**Comment by flisboac** [comment]
Thank you for preparing this, @thirappusuresh .

There doesn't seem to have any dependency hoisting or package linking in your example, and I wrote the helper to solve those specific use cases. My bad for not making this clear.

Well, turns out your use-case is much simpler, and you may not even need `react-native-monorepo-helper` at all. Try this in your rn-cli.config.json:

```js
const path = require('path');
module.exports = {
  projectRoot: __dirname,
  watchFolders: [path.resolve(__dirname, '..')],
  // If, for some reason, Haste becomes unable to resolve a
  // module, you can try messing around with 
  // "resolver.providesModuleNodeModules" and
  // "resolver.blacklistRE"
};
```

Please check this PR: https://github.com/thirappusuresh/monorepo-native/pull/1

In the future, I may consider adding support for complete auto-configuration, even when no hoisting or symlinking is involved. I also need to make some examples.

**Comment by thirappusuresh** [comment]
That worked, thanks a lot for your support.

**Comment by flisboac** [comment]
You're welcome! :)
